version: '3.4'
services:
  nginx:
    image: nginx:1.23.3-alpine
    container_name: bot_hub_app_nginx
    volumes:
      - .:/var/www/app
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bot_hub_network
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

  php-fpm:
    build:
      context: .docker/php-fpm
      dockerfile: Dockerfile
      target: php-fpm-prod
    container_name: bot_hub_php-fpm
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    networks:
      - bot_hub_network

  db:
    image: postgres:15
    container_name: bot_hub_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./.docker/postgresql_data:/var/lib/postgresql/data
    networks:
      - bot_hub_network
#
#  elasticsearch:
#    image: elasticsearch:8.7.0
#    container_name: bot_hub_es
#    environment:
#      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
#    volumes:
#      - ./.docker/elasticsearch/es_data:/usr/share/elasticsearch/data
#    networks:
#      - bot_hub_network
#
#  kibana:
#    image: kibana:8.7.0
#    container_name: bot_hub_kibana
#    networks:
#      - bot_hub_network
#    depends_on:
#      - elasticsearch
#
#  logstash:
#    image: logstash:8.7.0
#    container_name: bot_hub_logstash
#    depends_on:
#      - elasticsearch
#    networks:
#      - bot_hub_network

networks:
  bot_hub_network:
    driver: bridge
