version: '3.4'
services:
  nginx:
    image: nginx:1.23.3-alpine
    container_name: weather_app_nginx
    volumes:
      - .:/var/www/app
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - weather_app_network
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

  php-fpm:
    build:
      context: .docker/php-fpm
      dockerfile: Dockerfile
      target: php-fpm-prod
    container_name: weather_app_php-fpm
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    networks:
      - weather_app_network

  db:
    image: postgres:15
    container_name: weather_app_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./.docker/postgresql_data:/var/lib/postgresql/data
    networks:
      - weather_app_network

  elasticsearch:
    image: elasticsearch:8.7.0
    container_name: weather_app_es
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./.docker/elasticsearch/es_data:/usr/share/elasticsearch/data
    networks:
      - weather_app_network

  kibana:
    image: kibana:8.7.0
    container_name: weather_app_kibana
    networks:
      - weather_app_network
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:8.7.0
    container_name: weather_app_logstash
    depends_on:
      - elasticsearch
    networks:
      - weather_app_network

networks:
  weather_app_network:
    driver: bridge
